Utils/RXXEditor/RXXEditorForm.pas

Updated the UpdateList function. Now the exclusion will not merge.

Updating the UpdateList function in RXXEditor

---

Utils/Campaign builder/Unit1.dfm
Utils/Campaign builder/Unit1.pas
src/common/KM_Defaults.pas

New functionality: (Clear campaign; Show / Hide briefing; Edit campaign name) for Campaign Builder

New functionality for Campaign Builder

---

Utils/RXXEditor/RXXEditorForm.dfm
Utils/RXXEditor/RXXEditorForm.pas

Add checkBox for Image Stretch

Update RXX Editor (Add checkBox for Image Stretch)

---

src/houses/KM_HouseMarket.pas
src/scripting/KM_Scripting.pas
src/scripting/KM_ScriptingActions.pas
src/scripting/KM_ScriptingEvents.pas
src/units/KM_UnitTaskMining.pas

Event for ware being produced (all types of wares).

OnWareProduced

---

src/scripting/KM_Scripting.pas
src/scripting/KM_ScriptingActions.pas

Changed parameter type from array of AnsiString to TAnsiStringArray.

Arrayutilsfix

---

src/scripting/KM_ScriptingUtils.pas

Remove logs of empty array. (Last commit is missing in my repo because problems with git)

Arrayutils3

---

Installer/InstallerLib.iss

Updated compression method to lzma2
Added the ability to comment out the KAM license check
The default installation path has been changed. Now this is "C:\Games\KAM Remake"

Update Installer KAM Remake

---

src/gui/pages_maped/KM_GUIMapEdUnit.pas

Add Caption Condition for "ConditionBar_Unit"

---

Utils/TranslationManager/Unit_Text.pas

Fix bug with null indexes in TranslationManager

Fix bug with null indexes

---

src/ai/KM_AIMayor.pas

Fixes https://github.com/Kromster80/kam_remake/issues/3

Classical AI fix unconnected houses

---

src/KM_FormMain.pas

Solving the problem of scrolling with the mouse wheel in KAM Remake from @Stucuk from discord

Fix Mouse Wheel by @Stucuk from discord

---

src/scripting/KM_Scripting.pas
src/scripting/KM_ScriptingStates.pas
src/scripting/KM_ScriptingUtils.pas

Only partially tested.
This is the first time I am adding new dynamic scripts.

Add New Functions For Dynamic Script

---

src/KM_FogOfWar.pas
src/KM_Minimap.pas
src/common/KM_CommonTypes.pas
src/perflog/KM_DevPerfLog.pas
src/perflog/KM_DevPerfLogTypes.pas

On a large map UpdateMinimapFromGame runtime reduced from ~4.0ms to ~3.1ms

Minimap optimisations

---

src/game/KM_Game.pas

Reduces runtime in main thread from 55-60ms to 23-25ms

Perform autosave deletion/renaming in an async worker thread

---

src/ai/KM_AIGeneral.pas

Fixes the broken behavior for classic AI caused by my previous fix

Only fill closest positions for idle groups (on mission start)

---

src/KM_Music.pas

Моментальная смена устройства воспроизведения для библиотеки BASS

Fix BUG BASS Device

---

.gitattributes

Does it cause you any issues? It doesn't look necessary

My git client (SmartGit) is detecting all files as binary and refusing to merge/rebase unless I remove this

---

.gitignore
KaMProjectGroup.groupproj
Utils/AnimInterp/AnimInterp.dpr
Utils/AnimInterp/AnimInterp.dproj
Utils/AnimInterp/AnimInterpForm.dfm
Utils/AnimInterp/AnimInterpForm.pas
src/KM_Main.pas
src/common/KM_Defaults.pas
src/game/KM_Game.pas
src/render/KM_RenderPool.pas
src/res/KM_ResSpritesEdit.pas
src/units/KM_UnitGroup.pas
src/units/KM_UnitVisual.pas
src/units/KM_UnitWarrior.pas
src/units/KM_Units.pas
src/utils/KM_Utils.pas

Obviously it's not finished yet but I wanted to send a PR so I don't get conflicts with your branch. I also fixed a few bugs with interpolated render in this branch.
The animations won't be interpolated unless INTERPOLATED_ANIMS  is set to True.

Animation interpolation

---

src/gui/pages_game/KM_GUIGameResultsSP.pas

fixes https://trello.com/c/6kLAMQu1/1526-cant-uncheck-items-below-leather-armor-in-the-results-screen

fix SP stats interface dimensions

---

Utils/Runner/Runner_Game.pas
src/hands/KM_HandLogistics.pas

this is done because CACHE_DELIVERY_BIDS is defined only under ifdef WDC

enclose several places with CACHE_DELIVERY_BIDS into ifdef WDC

---

src/common/KM_CommonClasses.pas
src/game/misc/KM_RandomChecks.pas
src/utils/io/KM_FileIO.pas

FPC does not parse these conditions as expected, therefore I decided to slightly alter these conditions to make them work as expected

correct preprocessing conditions in case of usage of FPC

---

src/scripting/KM_Scripting.pas

use BobJenkinsHash() that is defined in Generics.Defaults of LCL

KM_Scripting unit: fix compilation with FPC under Lazarus

---

src/render/KM_RenderPool.pas
src/utils/KromUtils.pas

fix ambiguous call of GetLength

Linux FPC Lazarus: fix compilation of KM_RenderPool unit

---

src/terrain/KM_TerrainPainter.pas
src/utils/KromUtils.pas

fix ambiguous call of GetLength in TKMTerrainPainter.ApplyHeight

Linux FPC Lazarus: fix compilation KM_TerrainPainter unit

---

src/render/KM_RenderAux.pas
src/render/KM_RenderDebug.pas

such a similar work has already been accomplished in relation to GetInteger from KromUtils

fix compilation on Linux with FPC-3.2.2 and Lazarus-3.0 by disambiguating calls to TKMRenderAux.Quad()

---

data/locales.txt
data/text/text.ptb.libx

This PR updates the Brazilian Portuguese translation.
- Corrected outdated and missing lines
- Improved accuracy based on the latest English version
- Adjusted overly long text to fit UI elements
- Ensured consistency with previous translations
I have previous experience in translation, having started the Brazilian Portuguese translation back in 2009. However, my name is not currently in the credits. Is it okay if I add my name there?
Closes #220

Update Brazilian Portuguese translation

---

src/units/tasks/KM_UnitTaskMining.pas

Fixed an opportunity to use animal breeder abusing.

Animal breeder abuse fix.

---

src/net/KM_NetworkUtils.pas
src/net/KM_Networking.pas
src/net/KM_ServerQuery.pas

Fixed server display name. | symbol is replaced with ' '.

ServerDisplayName

---

src/scripting/KM_Scripting.pas
src/scripting/KM_ScriptingEvents.pas
src/scripting/KM_ScriptingTypes.pas
src/units/tasks/KM_UnitTaskDismiss.pas

Added new event and version X at events is changed to 15250.

OnUnitDissmised

---

src/scripting/KM_Scripting.pas
src/scripting/KM_ScriptingEvents.pas
src/units/KM_UnitGroup.pas

Added direction to OnGroupOrderMove event.

OnGroupOrderMove change.

---

src/game/gip/KM_GameInputProcess.pas
src/gui/pages_game/KM_GUIGameHouse.pas
src/houses/KM_HouseBarracks.pas
src/houses/KM_HouseStore.pas

Click with shift pressed on ware at storehouse or barrack locks/unlocks all wares for delivery/taking out.

AcceptOrBlockAllResources

---

src/common/KM_Defaults.pas

fixes https://trello.com/c/D8I68MLO/2321-tweak-army-power-numbers

Tweak army power graph values
