reyandme/kam_remake

src/units/KM_Units.pas
Killing problematic unit instead of rising error and crashing the game.
=> Unitonunwalkabletile fix

src/scripting/KM_Scripting.pas
Fix scripting error when having a global `array of string` / `array of anything containing a string`
=> Fix scripting error with stringarray

src/gui/pages_maped/terrain/KM_GUIMapEdTerrain.pas
It was before correction:
It became after the correction:
=> Fix the position of the buttons Undo and Rendo

Utils/RXXEditor/RXXEditorForm.dfm, Utils/RXXEditor/RXXEditorForm.pas
With this now you can select multiple images at once and export them into a selected directory. The exported files will be named as `<ID>.png` and `<ID>a.png`.
=> MultiSelect in RXXEditor with working Target Directory export

src/render/KM_RenderTerrain.pas
Improves runtime of UpdateVBO by about 2x on full zoom out of a 256x256 map (at 1920x1080 on i7-6700HQ with GTX 1060) from ~19ms to ~9ms. Less noticeable at normal zoom (<0.5ms before these optimisations).
1. Fixed unnecessary copying of dynamic arrays
2. Avoid resizing arrays during UpdateVBO, allocate the largest possible size needed on startup and use as much as needed
3. Avoid iterating over terrain twice by setting the verticies and indexes in a single pass
=> Update vbo optimisations

src/ai/newAI/KM_ArmyAttack.pas, src/ai/newAI/KM_ArmyAttackNew.pas, src/terrain/KM_Terrain.pas, src/units/actions/KM_UnitActionWalkTo.pas
Someone mentioned this on discord, where a serf dodges around an empty space because there was a unit in it when the route was calculated
=> Fixed serfs side stepping around unit that is no longer there

src/KM_Sound.pas, src/game/KM_Game.pas
Fixes 3 issues:
1. Crash caused by using Move on a record containing an AnsiString (now using TObjectList instead of manual array length management)
2. Looped, FadeMusic, and AudioFormat fields were not being saved
3. In multiplayer replays sounds wouldn't play because it was getting the wrong file path
=> Script sound fixes

src/KM_Minimap.pas, src/KM_Video.pas, src/common/KM_Defaults.pas, src/render/KM_Render.pas, src/render/KM_RenderPool.pas, src/render/KM_RenderTerrain.pas, src/res/KM_ResFonts.pas, src/res/KM_ResSprites.pas
Thanks to Krom's help and patience I've had another go at fixing the sprite bouncing (less hasty this time). @Kromster80 can you please review this when you have time? @reyandme please wait for Krom to have a look before merging.
Based on our discussion last night and reading the links you sent me, I guessed the problem is that sprites are not being rendered aligned to whole screen pixels, so sometimes due to rounding errors it samples from the wrong position.
In order to visualize this problem I added a debug boolean LINEAR_FILTER_SPRITES which filters rxTrees, rxUnits, and rxHouses atlases with GL_LINEAR. This means if sprites are not being sampled from pixel centers they will appear blurry (if sampled from center they will appear as normal). Sure enough, there's a vertical blur on most …
=> Sprite bounce fix

src/res/KM_Resource.pas
I noticed starting a mission was still taking a long time the second time after returning to menu, then I found this bug.
@reyandme Any idea why this check was there? It seems incorrect. Possibly to do with async loading? I see no reason not to update fDataState and delete temp buffers even if we are doing a forced reload.
=> Game resources were being reloaded the second time you start game

KaM_Remake.dpr, KaM_Remake.dproj, src/KM_Projectiles.pas, src/common/KM_Defaults.pas, src/game/KM_Game.pas, src/hands/KM_Hand.pas, src/hands/KM_HandsCollection.pas, src/render/KM_RenderPool.pas, src/units/KM_UnitVisual.pas, src/units/KM_UnitWarrior.pas, src/units/KM_Units.pas, src/units/KM_UnitsCollection.pas
Optional interpolated render for projectiles and units. Turned on with a switch in KM_Defaults.
Only position is interpolated, animations are still at the original framerate. This means it looks kind of weird like the units are sliding. Once we have full speed animations and make some tweaks it should look better.
Only really works at 1x speed, we need to rethink the way the timer works at higher speeds so we can do smooth rendering.
I want to get this batch of changes merged before I move on to the next stage (animations).
=> Interpolated render

src/KM_Controls.pas, src/gui/pages_game/KM_GUIGameResultsMP.pas
https://trello.com/c/UC7vBUQb/1234-in-game-statistics-scroll-up-automatically-on-refresh
=> Save position of wares list's scrollbar, when looking at Resources tab of in-game fullscreen statistics

.gitattributes, src/KM_Main.pas, src/game/KM_Game.pas, src/game/KM_GameApp.pas
Refactored all of the periodic tasks and TTimers into a single "main loop" in TKMMain.DoIdle. It handles:
- Game tick
- Render
- UpdateState
- UpdateStateIdle
- Sleeping until the next deadline when there's nothing to do
Periodic tasks like game ticks and render are scheduled so they occur at a consistent interval and we don't lose time (time slip) like we were with TTimer.
This code will not attempt to "catch up" if we something takes too long and we miss the scheduled tick (it will simply skip ahead to the next future tick schedule). The existing code in TKMGame will take care of catching up lost ticks, however it should now only occur when processing takes too long and we miss a tick.
This fixes the "jumpy" movements every ~1 second when interpolated render is on, which was caused by …
=> Tick rate fixes

src/common/KM_Defaults.pas, src/gui/pages_game/KM_GUIGameResultsMP.pas, src/hands/KM_HandStats.pas, src/scripting/KM_Scripting.pas, src/scripting/KM_ScriptingStates.pas
Added the scripting state `StatArmyPower`, which returns the army power of a specified player.
This PR moves the constant `WARRIORS_POWER_RATES` from `KM_GUIGameResultsMP.pas` to `KM_Defaults.pas`, which was done to make the constant accessible to `KM_HandStats.pas`.
One change by Rey is required: The comment describing at what revision this new state is added needs to be filled out.
=> Add StatArmyPower scripting state

src/KM_Controls.pas, src/KM_GameApp.pas, src/common/KM_CommonTypes.pas, src/common/KM_Points.pas, src/gui/KM_Viewport.pas, src/settings/KM_GameSettings.pas, src/terrain/KM_Terrain.pas
Implements new camera behaviour which allows moving the camera outside the map and unrestricted zooming beyond the boundaries of the map.
To choose different zoom behaviours, change `ZoomBehaviour` in `Kam Remake Settings.xml` to:
- 0: Original behaviour
- 1: Semi-restrictive zoom
- 2: Unrestricted zoom
**Note:**
- The minimap camera lines sometimes move "janky" (For example, the bottom line moves a pixel before the top line does, and also the other way around), I'm not certain if this can easily be fixed due to how the line positions are calculated
=> New zoom functionality behaviour

src/ai/KM_AIGeneral.pas, src/game/KM_GameSavePoints.pas, src/media/KM_ScriptSound.pas, src/unused/KM_PerfLog.pas
all current implementations of FP do not support generically sorting arrays like Delphi does, so we're switching to SortCustom procedure from KM_Sort unit when compiling with FPC
=> use custom sorting algo from KM_Sort unit when compiling with FPC

src/utils/algorithms/BinaryHeapGen.pas
this happened because constant had been defined within implementation section and used in a generic code what is prohibited by Free Pascal 
the constant must be defined in the interface to make it compile
=> FPC: fix Error: Global Generic template references static symtable

src/settings/KM_SettingsXML.pas
TKMSettingsXML.SaveToFile must override a virtual method of the base class with a correct type UnicodeString rather than an ordinary string
=> FPC Lazarus KM_SettingsXML unit compilation fix

src/settings/KM_MainSettings.pas
this gets free the module from double using Forms since there is Forms used in implementation section
=> unit KM_MainSettings: remove using Forms when FPC is defined

src/utils/KM_CommonUtils.pas
FPC on Linux does not have this function in system utilities, so let's define it in KM_CommonUtils
=> KM_CommonUtils unit: supply Unix FPC version with AtomicExchange

src/KM_GameApp.pas
this is impossible to assess performance on Linux since the latter does not have such functions used in the code in WDC version
=> disable gathering information about performance on Linux

src/settings/KM_GameAppSettings.pas
overriding must be done with the type that the base class provides
=> KM_GameAppSettings unit: correct TKMGameAppSettings.SaveToFile override

src/perflog/KM_DevPerfLogStack.pas
ignore adding secTime to list when compiled not only in WDC64 mode but also on Unix platform due to the same reason as for WDC64
=> KM_DevPerfLogStack unit: fix compilation on Unix platforms

src/utils/KM_CommonUtils.pas
for FPC + Unix mode we need AtomicIncrement and AtomicDecrement functions since they are absent in system modules and headers
=> KM_CommonUtils unit: add AtomicIncrement and AtomicDecrement functions

src/scripting/KM_ScriptingEvents.pas
Based on discussion in discord, the OnUnitAttacked event triggers when the unit is attacked by a tower, despite it's description.
Ref: https://discord.com/channels/338733130565287936/646798830192295936/1210504489505914890
=> Updated event comment to match behavior

src/houses/KM_Houses.pas
Take from workshops last added item first, because f.e. shields can be on top of each other in house
=> Change workshops LIFO items
